# docker-compose.yml
version: '3.1'

services:
  datastore:
    image: mongo
    ports:
      - 27017:27017
  consignment-cli:
    build: ./consignment-cli
    image: consignment-cli:latest
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    image: consignment-service:latest
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    image: vessel-service:latest
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    image: user-service:latest
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  database:
    image: postgres
    ports:
      - 5432:5432

  user-cli:
    build: ./user-cli
    image: user-cli:latest
    environment:
      MICRO_REGISTRY: "mdns"


